include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_NAME "rk2")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_CONTACT "tananaa")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Observer pattern")
set(CPACK_DEBIAN_PACKAGE_NAME "rk2-observer")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_GENERATOR "DEB")
include(CPack)
