name: GTests

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'

permissions:
  contents: write    # <---- ГЛАВНАЯ КОМАНДА, которая все исправила

jobs:
  gtest_build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install GoogleTest
      run: |
        sudo apt update
        sudo apt install -y libgtest-dev cmake build-essential
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
    
    - name: Configure CMake with tests
      run: cmake -H. -B_build -DBUILD_TESTS=ON
    
    - name: Build with GTest
      run: cmake --build _build
    
    - name: Run GoogleTest tests
      run: ./_build/tests

  release:
    needs: gtest_build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write    # <---- И ЗДЕСЬ ТОЖЕ
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      run: |
        mkdir -p _build
        cd _build
        cmake .. 
        make
        cpack -G DEB
        cd ..
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: _build/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
